site_name: Nuvolos CLI
theme: readthedocs
nav:
  - Home: index.md
  - Installation: install.md
  - Quickstart: quickstart.md
  - Guides:
    - Launch scaled applications: launch_scaled_apps.md
    - Execute commands: execute_commands.md
    - List running applications: list_running_applications.md
  - Management Documentation:
    - Instance Management: instance_management.md
    - Application Management: app_management.md
    - Session Management: session_management.md
    - Snapshot Management: snapshot_management.md
    - Image Management: image_management.md
    - Image Families: image_families_management.md
    - Image Links: image_links_management.md
    - Space Management: space_management.md
    - Files Management: files_management.md
    - Tables Management: tables_management.md
    - Distribution Management: distribution_management.md
  - Command reference: commands.md


markdown_extensions:
  - mkdocs-click
  - attr_list
  - admonition
