name: Release package to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Pull and checkout branch
        uses: actions/checkout@master

      - name: Install python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: 3.8

      - name: Build and upload package
        run: |
          echo "Installing setuptools"
          pip install -U setuptools
          echo "Installing twine"
          pip install -U twine
          echo "Installing build"
          pip install -U build
          echo "Installing packaging"
          pip install -U "packaging>=25.0"
          echo "Building package"
          python -m build
          echo "Uploading package"
          twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
